name: JSON Validation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Validate JSON
      run: python -m json.tool public/manifest.json
